timeout: 3
wallpaper: boot():/EFI/wallpaper.jpg

/QuantumNEC
    protocol: limine
    kernel_path: boot():/OS/micro_kernel.elf
    module_path: boot():/OS/bin/filesystem
    paging_mode: 4level
    resolution: 1920x1080x32