add_rules("mode.debug", "mode.release")
-- add_cxxflags(" -m64 \
--                -fno-builtin \
--                -mcmodel=large \
--                -ffreestanding \
--                -fno-stack-protector \
--                -nostdlib \
--                -nostartfiles \
--                -fstrength-reduce \
--                -falign-loops \
--                -falign-jumps \
--                -fno-strict-aliasing \
--                -fno-common \
--                -fno-rtti \
--                -fno-exceptions \
--                -mno-red-zone \
--                -fno-stack-check \
--                -fno-lto \
--                -Wall \
--                -Wextra \
--                -fPIC \
--                ")
-- add_includedirs("../Include", "../Boot/limine/")
-- set_optimize("none")
-- set_languages("c17", "c++23")
target("cxx")
    set_kind("static")
-- target("cxx")
--     set_kind("static")
--     add_files("./*.cpp" )
--     before_build(function (target) 
--         print("开始编译库文件")
--         end)
--     -- on_link(function(target)
--     --     print("编译与链接库文件生成静态库")
--     --     object_dir = target:objectdir()
--     --     run_dir = target:rundir()
--     --     object_string = ""
--     --     for key,val in pairs(target:objectfiles()) do 
--     --         object_string = object_string..val.." "
--     --     end 
--     --     os.mkdir(run_dir)
--     --     os.exec("ar -rc "..run_dir.."/libcxx.a "..object_string.."")
--     -- end)
--     after_build(function (target) 
--         run_dir = target:rundir()
--         print("静态库编译完成，在"..run_dir.."")
--     end)